---
# vars file for deploy-lex-core-service

# For script
release_name: "{{ network_alias_cb_integration_framework }}"
template_compose_file_name: cb-integration-framework.j2
template_env_file_name: cb-integration-framework-env.j2
compose_file_name: "{{ service_cb_integration_framework }}.yml"
env_file_name: "{{ service_cb_integration_framework }}.env"
helm_env_file_location: "../helm_charts/igot-deploy/templates/"
helm_env_file_name: "{{ helm_env_file_location }}/{{ service_cb_integration_framework }}.env"
#chart_path: "../kubernetes-deploy/cb-integration-framework"

env_file_deployment_location: "{{ env_files_dir }}/{{ env_file_name }}"
compose_file_deployment_location: "{{ compose_files_dir }}/{{ compose_file_name }}"
user_friendly_name: cb_integration_framework

# For service
application_port: "{{ service_cb_integration_framework_port }}"
image_name: "{{ image_cb_integration_framework }}"
tag: "{{ tags_cb_integration_framework }}"
host_port: "{{ application_port }}"
docker_port: "{{ application_port }}"
replicas: "{{ service_replicas_cb_integration_framework }}"
reserved_memory: "{{ service_mem_reserved_cb_integration_framework }}"
limited_memory: "{{ service_mem_limit_cb_integration_framework }}"
#limited_memory: 2048M
health_check_endpoint: http://127.0.0.1:{{ docker_port }}/contentValidation/actuator/health
network_alias_name: "{{ network_alias_cb_integration_framework }}"
docker_service_stack_name: lms
docker_service_name: "{{ service_cb_integration_framework }}"
force_reload: "{{ force_reload_cb_integration_framework }}"
