---
- hosts: local
  gather_facts: no
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  vars_files:
    - "{{inventory_dir}}/group_vars/all.yml"
    - "{{inventory_dir}}/common.yml"
  roles:
    - role: deploy-igot
      tags: ["always"]
      when: "'deploy-static-domain' not in ansible_run_tags"
    - role: deploy-static-domain
      tags:
        - deploy-static-domain
