---
- hosts: localhost
  #become: yes
  vars_files:
    - "{{inventory_dir}}/secrets.yml"
  roles:
    - role: artifacts-upload-gcp
      vars:
      service_account: "{{ gcp_artifcats_upload_service_account }}"
      tags: gcp
    - role: artifacts-upload-azure
      environment:
        AZURE_STORAGE_ACCOUNT: "{{ sunbird_artifact_storage_account_name }}"
        AZURE_STORAGE_SAS_TOKEN: "{{ sunbird_artifact_storage_account_sas }}"
      tags: azure
